### ISSUE TITLE
РЕШЕНИЕ: откл. плашек и REG к обработчику протокола URL

### ISSUE THREAD

**Issue by vadimlitvinenko87** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#1]
Решение как убрать плашки об ОС и неподдерживаемом аргументе.
(собственно два аргумента к ярлыку --no-sandbox --test-type)
REG файл добавляет запрет на показ одной плашки и дополняет аргументами запись обработчика протокола URL.

----------------------------------------------
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Policies\Google\Chrome]
"SuppressUnsupportedOSWarning"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\ChromeHTML\shell\open\command]
@="\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\" --no-sandbox --test-type --single-argument %1"

**Comment by Blaukovitch** [comment]
Спасибо!
В принципе, ключ **--no-sandbox** можно "вшить" на уровне патча и забыть за него. При всём своем желании Windows 7 SP1 не поддерживает митигации для процесса (process mitigation), так что из всего SANDBOX там (как и в XP/Server 2003, кстати) "DEP protection" по дефолту будет работать только. Sandbox нужен только для _gpu_ процесса (`--type=gpu-process`), чтобы его в правах ограничить. В принципе для этого gpu-process можно сделать свой sandbox с "блекджеком и ...", но не нанимался в Google работать.
На уровне патча было пофикшено "OS Warning" для x64.

**Comment by vadimlitvinenko87** [comment]
--test-type Убирает плашку о неподдерживаемом аргументе. Всё работает без плашек теперь, REG в первом комменте поправил.

**Comment by vadimlitvinenko87** [comment]
Я не настаиваю заморачиваться, просто кинул инфу в ветку, т.к. народ полюбому будет долбиться искать как эти плашки убрать, плюс прикол с ярлыками, которые не открываются если не менять через REG запись обработчика протокола.
