### ISSUE TITLE
Consider making crack’s process or source code public

### ISSUE THREAD

**Issue by gz83** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#11]
Thank you very much for your work. Could you please consider making the crack process or source code public?

**Comment by Blaukovitch** [comment]
@gz83, hi!
Some information about this you can find here (after translate):
https://habr.com/ru/articles/752692/ 
https://xakep.ru/2023/08/10/chrome-for-windows-7/

Public code in _API-MS-WIN_XP_ repository.

Maybe in the future I'll release a more detailed article with documentation on hacking the next versions of Chrome browser for Windows 7. Google is already aware of **this crack**, so they have started to slowly introduce code to counteract it, but so far it's not a big deal.

**Comment by Blaukovitch** [comment]
updated source code of API-MS..., kernel64, user64 and etc libs in [API-MS repo](https://github.com/Blaukovitch/API-MS-WIN_XP)

**Comment by gz83** [comment]
> updated source code of API-MS..., kernel64, user64 and etc libs in [API-MS repo](https://github.com/Blaukovitch/API-MS-WIN_XP)

Thank you

**Comment by Blaukovitch** [comment]
>  Consider making crack’s process 

https://habr.com/ru/articles/789120/ - **more technical info** and piracy.
