### ISSUE TITLE
BRAVE_BROWSER _Windows7_CRACK!!

### ISSUE THREAD

**Issue by krimnassim** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#15]
Hi,thanks for making this project and keeping browsing possible on w7,i have a question is it possible to make a crack for the latest brave browser for 32bit W7 and I appreciate ur work thanks.
![images](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/62130284/7a875234-4f87-4cb0-bde3-c7c31e99d43d)

**Comment by Blaukovitch** [comment]
@krimnassim, great for you:
[BRAVE 120..120 Windows 7](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/releases/tag/brave)
![image](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/116763547/36eb039f-1e45-4ea0-bb58-3333aa49cf58)

**Thanks for you support!**

**Comment by krimnassim** [comment]
that was fast :)thank u,one more thing if u can make {BRAVE STANDALONE SETUP32} that will be nice and thanks again for ur work.

**Comment by Blaukovitch** [comment]
>{BRAVE STANDALONE SETUP32}

I understand that it would be more convenient to have an **installation package**, but for now you can just download the latest official version and then replace the files from my archive in it - it's faster at the moment.

**Comment by krimnassim** [comment]
i will try it,if it worked that nice if not i will use the portable version,maybe we get standalone version in future updates thank u and good night:)

**Comment by krimnassim** [comment]
Hi,i tried brave portable it worked great on my pc but when i tried to open it on my w7 laptop i got this error {the procedure entry point SetDefaultDllDirectories could not be located in the dynamic link libary KERNEL32.dll} how to fix it? and thanks for the help.
![Capture](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/62130284/c6625675-361c-44b3-981f-57702a9dd95a)

**Comment by adeii** [comment]
Yes! Thanks for kernel64.dll with missing functions (K32GetModuleFileNameExA, GetThreadStackGuarantee, WritePrivateProfileStringW). Portable version with --no-sandbox --enable-unsafe-webgpu will crash/forced close browser occasional on Win 7.

**Comment by Blaukovitch** [comment]
> Hi,i tried brave portable it worked great on my pc but when i tried to open it on my w7 laptop i got this error {the procedure entry point SetDefaultDllDirectories could not be located in the dynamic link libary KERNEL32.dll} how to fix it? and thanks for the help.

Update you Windows 7 in laptop! 
[SetDefaultDllDirectories](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-setdefaultdlldirectories) provide [**KB2533623**](https://support.microsoft.com/en-us/topic/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution-486ea436-2d47-27e5-6cb9-26ab7230c704) on Windows 7

**Comment by darkalexis1990** [comment]
all these people using outdated windows 7 ....

@Blaukovitch anythin in progress from spotify? ^_^
