### ISSUE TITLE
I need Chrome 120 on Windows 7

### ISSUE THREAD

**Issue by Saswat2005** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#8]
I have installed Chrome 118 on Windows 7 with your patch. Can @Blaukovitch help me to patch Chrome 120 on Windows 7 because Chrome 120 is the best version ever as I love Windows 7.

**Comment by Blaukovitch** [comment]
Hi!
@Saswat2005, [ver 120](/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/releases/tag/120/) for you!  

But SANDBOX still unstable (however improve) .

p.s. I love Windows 7 too.
